CREATE TABLE IF NOT EXISTS MYSEQUENCE(
    SEQ_NAME VARCHAR2(100 CHAR),
    SEQ_VALUE NUMBER(10,0),
    PRIMARY KEY (SEQ_NAME)
    ) WITH "ATOMICITY=TRANSACTIONAL_SNAPSHOT";;

INSERT INTO MYSEQUENCE(SEQ_NAME, SEQ_VALUE) values ('SEQ1', 1);